### ISSUE TITLE
Visual Studio 2022 build

### ISSUE THREAD

**Issue by duncansmart** [jcansdale/TestDriven.Net-Issues#157]
As Visual Studio 2022's [release is approaching](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-1-now-available/), can we get a build for it? I've tried hacking the VSIX's `extension.vsixmanifest` file by adding an InstallationTarget like so:

    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.0,18.0)">
      <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>

Which gets it to install, but then when I try the ad-hoc test runner I get the following in ActivityLog.xml:
```
CreateInstance failed for package [TestDrivenPackage]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
```

**Comment by Mike-E-angelo** [comment]
Any luck with this issue, by chance?  R[# 2021.2 just released 2022 support](https://resharper-support.jetbrains.com/hc/en-us/articles/4404930135570) today so I am trying to hack all my 2019 extensions over and am running into the same error. 😭

**Comment by BowserKingKoopa** [comment]
I need this as well. I can't live without my TestDriven.net

**Comment by jimnkey** [comment]
```

                                                        ,▄▄,     ,,,,
                                                    ,▄███████Ç,╓██████▄
                                                   ,██▀▀██▌▐███████▄╙███
                                                   ███  ╠██U███` ╙██▌]██▌
                                                  ███   ]██▓██`   ▐██░██▌▄,
                                                 ▓██`   ▐████▌    ▐██▄██████▄
                                                ▄██`    ████▌     ▐██████▄ ███
                                               ▄██`    ▐████      ███  ╙██W]██[
                                              ▄██╜     ████      ▐██`   ███ ██▌
                                             ███`     ▓███      ╓██▌    ▐██ ██▌
                                            ███`     ▐███      ┌██▌     ██▌ ██▌
                                          ╓███      ]███       ███     ]██▌]██M
                      ,▄▄▄▄█████▄,       ╓██▌      ╓██▀       ███      ▓██▄████▄
                     j██▀▀▀████▀███╖    ▄██▀      ╓██▀       ███`     ▐██████▌▀██╕
                      ██▌   `▀██Ç▀██▄  ███╜      á██▀       ███`     ,██▌  ▀██ ▓██
                      ▐██     ▐██C▐██▄███       ▄██▀      ,███       ███   ]██∩▐██
                      ]██U     ███ ▓███▀       ███'      ╓███       ███    ]██`▐██
                      ]██U     ▐██U▐██▀       "▀▀       ╓██▌       ███     ▐██ ██▌
                      ▐██       █████╜                 ▄██▀       ███`    ,██▌]██M
                      ▐██       ▐███`                 ▐██╜      ┌███      ██▌ ██▌
                      ███      ,███                    `       á██▌      ▓██ ▐██
                      ██▌     ,███                            ▄██▀      ▄██ ╓██`
                     ]██▌     ██▌                            ▓██`      ▓██ ┌██▀
                     ▐██     ╙█▀                                      ███ ╓██▀
                     ▐██                                            ╓██▀ ╓██▀
                     ▐██                                           ▄██╜ ╓██╜
                     ▓██                                          ███  ▐██'
                     ▐██                                        ╓██▀  ▄██`
                     ▐██C                                      ▄██╜  ▓██
                      ███                                     ▄██   ▓██
                      "███                                  ,██▌   ███
                        ███╖                               ╓██▀   ███
                     ,▄██▀██                              ▄██▀  ╓██▀
                   ╓███▀                                ╓██▀   ▄██▀
                 ▄███`                                ╓███╜  ╓███
              ╓▄██▀                                 ▄███▀  ╓███▀
            ▄███▀                                ╓▄██▀`  ╓███▀
         ╓███▀`                               ╓▄███▀  ,▄███▀
      ,▄███▀                               ▄████▀▄▄█████▀`
     ███▀`                               ▄██▀╙   ▐███▀"
                                       ▄██▀     ▄██▀
                                     ▄██▀     ,███
                                   ▄██▀      ╓██▀
                                ,▄██▀       ▄██▀
                              ,▄██▀        ███'
                             ▄██▀        ╓███
                          ,▄██▀         g██▀
                        ╓███▀          ▄██╜
                      ╓███▀          ╓███
                       ▀"           ▐██▀
                                     ▀
    
---
^[ [^ascii ^art ^generator](http://asciiart.club) ^] 

```
:)

**Comment by blopez** [comment]
Hi, any news on this for VS2022?

**Comment by danhol86** [comment]
I ended up building my own version. I only use it for running the function at my cursor. If only need this then let me know.

**Comment by BowserKingKoopa** [comment]
> I ended up building my own version. I only use it for running the function at my cursor. If only need this then let me know.

Yes I'd like to get a copy of that. I only use it to run the code at my cursor as well.

**Comment by chucker** [comment]
Same. For regular unit testing, VS is OK. For quickly turning _any_ static method (even when the project is a library) into an entry point, this extension is terrific.

**Comment by mxmissile** [comment]
@danhole86 will yours run a unit test at the cursor? If so, I'm game for sure!!!

**Comment by danhol86** [comment]
Added extension to the marketplace "RunFromCursor". Will be putting code on github shortly. 2 commands currently to bind to. "DebugCodeAtCursor" and "RerunCodeAtCursor"

**Comment by mxmissile** [comment]
Thanks for this!!  However I'm getting this error when running either command:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/235144/156401044-e7c4bc4f-cec3-493a-b96c-3d3006d1628c.png">

If you need anything from me, happy to help!

**Comment by danhol86** [comment]
Maybe worth using below link until I get github up and running. 
https://marketplace.visualstudio.com/items?itemName=AgileAutomations.runfromcursoraa&ssr=false#qna

**Comment by BowserKingKoopa** [comment]
I'm getting the same error as mxmissile above on extension version 1.13.

**Comment by danhol86** [comment]
Issue solved in 1.15. Please use below link for any issues:
https://marketplace.visualstudio.com/items?itemName=AgileAutomations.runfromcursoraa&ssr=false#overview

**Comment by BowserKingKoopa** [comment]
Upgraded to 1.15. Now the "Debug Code At Cursor" option builds the code but doesn't seem to run the code. And the "ReRun Code at Cursor" Option complains about a missing Microsoft.CodeAnalysis dll. I added that package to my project but it still complains.

**Comment by danhol86** [comment]
> Upgraded to 1.15. Now the "Debug Code At Cursor" option builds the code but doesn't seem to run the code. And the "ReRun Code at Cursor" Option complains about a missing Microsoft.CodeAnalysis dll. I added that package to my project but it still complains.

Please try v3879. For some reason Microsoft didn't pack all required DLLs into the vsix. You shouldn't need to install anything extra to your proj

**Comment by BowserKingKoopa** [comment]
> Please try v3879. For some reason Microsoft didn't pack all required DLLs into the vsix. You shouldn't need to install anything extra to your proj

Version 1.3879 is working for me. Thank you very much.

**Comment by mxmissile** [comment]
@danhol86 do you have a repo setup for this? Have an issue I would like to discuss, dont want to muddy up this thread.

**Comment by BowserKingKoopa** [comment]
@danhol86 This doesn't seem to work with async methods.  It doesn't wait for them to finish.

**Comment by danhol86** [comment]
> @danhol86 do you have a repo setup for this? Have an issue I would like to discuss, dont want to muddy up this thread.

Please message in q&a here for now. Thanks 
https://marketplace.visualstudio.com/items?itemName=AgileAutomations.runfromcursoraa&ssr=false#qna
