### ISSUE TITLE
Can't evaluate property as "Ad hoc" test in NUnit project

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#20]
```
------ Test started: Assembly: TestDriven.NetCore.TestRunner.Tests.dll ------

Test 'P:TestDriven.NetCore.TestRunner.Tests.TargetAssemblyUtilities.NetCoreAssemblyFile' failed: Member type not supported: System.Reflection.RuntimePropertyInfo
	System.Exception: Member type not supported: System.Reflection.RuntimePropertyInfo
	at NUnitTDNet.Adapter.Utilities.GetWhereForTarget(Assembly assembly, MemberInfo member)
	at NUnitTDNet.Adapter.EngineTestRunner.RunMember(ITestListener testListener, Assembly assembly, MemberInfo member)
	at TestDriven.TestRunner.AdaptorTestRunner.Run(ITestListener testListener, ITraceListener traceListener, String assemblyPath, String testPath)
	at TestDriven.TestRunner.ThreadTestRunner.Runner.Run()

0 passed, 1 failed, 0 skipped, took 0.55 seconds (NUnit 3.x).
```

**Comment by jcansdale** [comment]
Wend live in TestDriven.NET-3.10.3323 RTM.
