### ISSUE TITLE
Can't evaluate "Ad hoc" properties in NUnit test projects

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TestDriven.Net-Issues#28]
See: https://github.com/nunit/nunit3-tdnet-adapter/issues/7

**Comment by jcansdale** [comment]
Was failing with:

```
------ Test started: Assembly: ClassLibrary7.dll ------

Test 'P:ClassLibrary7.Class1.SystemVersion' failed: Member type not supported: System.Reflection.RuntimePropertyInfo
	System.Exception: Member type not supported: System.Reflection.RuntimePropertyInfo
	at NUnitTDNet.Adapter.Utilities.GetTestPath(MemberInfo member)
	at NUnitTDNet.Adapter.EngineTestRunner.RunMember(ITestListener testListener, Assembly assembly, MemberInfo member)
	at TestDriven.TestRunner.AdaptorTestRunner.Run(ITestListener testListener, ITraceListener traceListener, String assemblyPath, String testPath)
	at TestDriven.TestRunner.ThreadTestRunner.Runner.Run()

0 passed, 1 failed, 0 skipped, took 0.51 seconds (NUnit 3.2.1).
```
